---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sip.livekit-sip.io
  resources:
  - egressconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sip.livekit-sip.io
  resources:
  - sipdispatchrules
  - sipinboundtrunks
  - sipoutboundtrunks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sip.livekit-sip.io
  resources:
  - sipdispatchrules/finalizers
  - sipinboundtrunks/finalizers
  - sipoutboundtrunks/finalizers
  verbs:
  - update
- apiGroups:
  - sip.livekit-sip.io
  resources:
  - sipdispatchrules/status
  - sipinboundtrunks/status
  - sipoutboundtrunks/status
  verbs:
  - get
  - patch
  - update
