---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "livekit-sip-operator.fullname" . }}-manager-role
  labels:
    {{- include "livekit-sip-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sip.livekit-sip.io
  resources:
  - egressconfigs
  - siptrunkconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sip.livekit-sip.io
  resources:
  - agentroutes
  - sipdispatchrules
  - sipinboundtrunks
  - sipnumbers
  - sipoutboundtrunks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sip.livekit-sip.io
  resources:
  - agentroutes/finalizers
  - sipdispatchrules/finalizers
  - sipinboundtrunks/finalizers
  - sipnumbers/finalizers
  - sipoutboundtrunks/finalizers
  verbs:
  - update
- apiGroups:
  - sip.livekit-sip.io
  resources:
  - agentroutes/status
  - sipdispatchrules/status
  - sipinboundtrunks/status
  - sipnumbers/status
  - sipoutboundtrunks/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "livekit-sip-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "livekit-sip-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "livekit-sip-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "livekit-sip-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
{{- if .Values.leaderElection.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "livekit-sip-operator.fullname" . }}-leader-election-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "livekit-sip-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "livekit-sip-operator.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "livekit-sip-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "livekit-sip-operator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "livekit-sip-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
