apiVersion: sip.livekit-sip.io/v1alpha1
kind: SIPDispatchRule
metadata:
  labels:
    app.kubernetes.io/name: livekit-sip-operator
    app.kubernetes.io/managed-by: kustomize
  name: sipdispatchrule-sample
spec:
  livekitRef:
    service: livekit-server
    secretName: livekit-credentials
  name: my-dispatch-rule
  type: individual
  individual:
    roomPrefix: call-
  hidePhoneNumber: true
  mediaEncryption: disable
  roomConfig:
    agents:
      - agentName: observatory-agent
    egress:
      room:
        roomName: my-room
        audioOnly: true
        audioMixing: DEFAULT_MIXING
        fileOutputs:
          - filepath: "recordings/{room_id}/recording.ogg"
            egressConfigRef:
              name: minio-egress
