apiVersion: sip.livekit-sip.io/v1alpha1
kind: LivekitAgent
metadata:
  labels:
    app.kubernetes.io/name: livekit-sip-operator
    app.kubernetes.io/managed-by: kustomize
  name: support-agent
spec:
  agentName: support-agent
  deploymentRef:
    name: support-agent
  metadata:
    language: en
    capabilities: voice,dtmf
