//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRoute) DeepCopyInto(out *AgentRoute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRoute.
func (in *AgentRoute) DeepCopy() *AgentRoute {
	if in == nil {
		return nil
	}
	out := new(AgentRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRoute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRouteList) DeepCopyInto(out *AgentRouteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRouteList.
func (in *AgentRouteList) DeepCopy() *AgentRouteList {
	if in == nil {
		return nil
	}
	out := new(AgentRouteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRouteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRouteSpec) DeepCopyInto(out *AgentRouteSpec) {
	*out = *in
	out.LivekitRef = in.LivekitRef
	if in.AgentRef != nil {
		in, out := &in.AgentRef, &out.AgentRef
		*out = new(LivekitAgentReference)
		**out = **in
	}
	if in.NumberRefs != nil {
		in, out := &in.NumberRefs, &out.NumberRefs
		*out = make([]SIPNumberReference, len(*in))
		copy(*out, *in)
	}
	if in.Individual != nil {
		in, out := &in.Individual, &out.Individual
		*out = new(SIPDispatchRuleIndividual)
		**out = **in
	}
	if in.RoomConfig != nil {
		in, out := &in.RoomConfig, &out.RoomConfig
		*out = new(RoomConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRouteSpec.
func (in *AgentRouteSpec) DeepCopy() *AgentRouteSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRouteStatus) DeepCopyInto(out *AgentRouteStatus) {
	*out = *in
	if in.TrunkIDs != nil {
		in, out := &in.TrunkIDs, &out.TrunkIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastSyncedAt != nil {
		in, out := &in.LastSyncedAt, &out.LastSyncedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRouteStatus.
func (in *AgentRouteStatus) DeepCopy() *AgentRouteStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRouteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliOSSConfig) DeepCopyInto(out *AliOSSConfig) {
	*out = *in
	out.AccessKeyRef = in.AccessKeyRef
	out.SecretKeyRef = in.SecretKeyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliOSSConfig.
func (in *AliOSSConfig) DeepCopy() *AliOSSConfig {
	if in == nil {
		return nil
	}
	out := new(AliOSSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureConfig) DeepCopyInto(out *AzureConfig) {
	*out = *in
	out.AccountNameRef = in.AccountNameRef
	out.AccountKeyRef = in.AccountKeyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureConfig.
func (in *AzureConfig) DeepCopy() *AzureConfig {
	if in == nil {
		return nil
	}
	out := new(AzureConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentReference) DeepCopyInto(out *DeploymentReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentReference.
func (in *DeploymentReference) DeepCopy() *DeploymentReference {
	if in == nil {
		return nil
	}
	out := new(DeploymentReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressConfig) DeepCopyInto(out *EgressConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressConfig.
func (in *EgressConfig) DeepCopy() *EgressConfig {
	if in == nil {
		return nil
	}
	out := new(EgressConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EgressConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressConfigList) DeepCopyInto(out *EgressConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EgressConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressConfigList.
func (in *EgressConfigList) DeepCopy() *EgressConfigList {
	if in == nil {
		return nil
	}
	out := new(EgressConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EgressConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressConfigReference) DeepCopyInto(out *EgressConfigReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressConfigReference.
func (in *EgressConfigReference) DeepCopy() *EgressConfigReference {
	if in == nil {
		return nil
	}
	out := new(EgressConfigReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressConfigSpec) DeepCopyInto(out *EgressConfigSpec) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3Config)
		(*in).DeepCopyInto(*out)
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(AzureConfig)
		**out = **in
	}
	if in.GCP != nil {
		in, out := &in.GCP, &out.GCP
		*out = new(GCPConfig)
		**out = **in
	}
	if in.AliOSS != nil {
		in, out := &in.AliOSS, &out.AliOSS
		*out = new(AliOSSConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressConfigSpec.
func (in *EgressConfigSpec) DeepCopy() *EgressConfigSpec {
	if in == nil {
		return nil
	}
	out := new(EgressConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressConfigStatus) DeepCopyInto(out *EgressConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressConfigStatus.
func (in *EgressConfigStatus) DeepCopy() *EgressConfigStatus {
	if in == nil {
		return nil
	}
	out := new(EgressConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileOutput) DeepCopyInto(out *FileOutput) {
	*out = *in
	out.EgressConfigRef = in.EgressConfigRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileOutput.
func (in *FileOutput) DeepCopy() *FileOutput {
	if in == nil {
		return nil
	}
	out := new(FileOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPConfig) DeepCopyInto(out *GCPConfig) {
	*out = *in
	out.CredentialsRef = in.CredentialsRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPConfig.
func (in *GCPConfig) DeepCopy() *GCPConfig {
	if in == nil {
		return nil
	}
	out := new(GCPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LivekitAgent) DeepCopyInto(out *LivekitAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LivekitAgent.
func (in *LivekitAgent) DeepCopy() *LivekitAgent {
	if in == nil {
		return nil
	}
	out := new(LivekitAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LivekitAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LivekitAgentList) DeepCopyInto(out *LivekitAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LivekitAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LivekitAgentList.
func (in *LivekitAgentList) DeepCopy() *LivekitAgentList {
	if in == nil {
		return nil
	}
	out := new(LivekitAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LivekitAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LivekitAgentReference) DeepCopyInto(out *LivekitAgentReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LivekitAgentReference.
func (in *LivekitAgentReference) DeepCopy() *LivekitAgentReference {
	if in == nil {
		return nil
	}
	out := new(LivekitAgentReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LivekitAgentSpec) DeepCopyInto(out *LivekitAgentSpec) {
	*out = *in
	if in.DeploymentRef != nil {
		in, out := &in.DeploymentRef, &out.DeploymentRef
		*out = new(DeploymentReference)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LivekitAgentSpec.
func (in *LivekitAgentSpec) DeepCopy() *LivekitAgentSpec {
	if in == nil {
		return nil
	}
	out := new(LivekitAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LivekitAgentStatus) DeepCopyInto(out *LivekitAgentStatus) {
	*out = *in
	if in.LastSyncedAt != nil {
		in, out := &in.LastSyncedAt, &out.LastSyncedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LivekitAgentStatus.
func (in *LivekitAgentStatus) DeepCopy() *LivekitAgentStatus {
	if in == nil {
		return nil
	}
	out := new(LivekitAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LivekitReference) DeepCopyInto(out *LivekitReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LivekitReference.
func (in *LivekitReference) DeepCopy() *LivekitReference {
	if in == nil {
		return nil
	}
	out := new(LivekitReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoomAgentDispatchConfig) DeepCopyInto(out *RoomAgentDispatchConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoomAgentDispatchConfig.
func (in *RoomAgentDispatchConfig) DeepCopy() *RoomAgentDispatchConfig {
	if in == nil {
		return nil
	}
	out := new(RoomAgentDispatchConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoomCompositeEgress) DeepCopyInto(out *RoomCompositeEgress) {
	*out = *in
	if in.FileOutputs != nil {
		in, out := &in.FileOutputs, &out.FileOutputs
		*out = make([]FileOutput, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoomCompositeEgress.
func (in *RoomCompositeEgress) DeepCopy() *RoomCompositeEgress {
	if in == nil {
		return nil
	}
	out := new(RoomCompositeEgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoomConfig) DeepCopyInto(out *RoomConfig) {
	*out = *in
	if in.Agents != nil {
		in, out := &in.Agents, &out.Agents
		*out = make([]RoomAgentDispatchConfig, len(*in))
		copy(*out, *in)
	}
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = new(RoomEgressConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoomConfig.
func (in *RoomConfig) DeepCopy() *RoomConfig {
	if in == nil {
		return nil
	}
	out := new(RoomConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoomEgressConfig) DeepCopyInto(out *RoomEgressConfig) {
	*out = *in
	if in.Room != nil {
		in, out := &in.Room, &out.Room
		*out = new(RoomCompositeEgress)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoomEgressConfig.
func (in *RoomEgressConfig) DeepCopy() *RoomEgressConfig {
	if in == nil {
		return nil
	}
	out := new(RoomEgressConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Config) DeepCopyInto(out *S3Config) {
	*out = *in
	out.AccessKeyRef = in.AccessKeyRef
	out.SecretKeyRef = in.SecretKeyRef
	if in.SessionTokenRef != nil {
		in, out := &in.SessionTokenRef, &out.SessionTokenRef
		*out = new(SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Config.
func (in *S3Config) DeepCopy() *S3Config {
	if in == nil {
		return nil
	}
	out := new(S3Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPDispatchRule) DeepCopyInto(out *SIPDispatchRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPDispatchRule.
func (in *SIPDispatchRule) DeepCopy() *SIPDispatchRule {
	if in == nil {
		return nil
	}
	out := new(SIPDispatchRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SIPDispatchRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPDispatchRuleCallee) DeepCopyInto(out *SIPDispatchRuleCallee) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPDispatchRuleCallee.
func (in *SIPDispatchRuleCallee) DeepCopy() *SIPDispatchRuleCallee {
	if in == nil {
		return nil
	}
	out := new(SIPDispatchRuleCallee)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPDispatchRuleDirect) DeepCopyInto(out *SIPDispatchRuleDirect) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPDispatchRuleDirect.
func (in *SIPDispatchRuleDirect) DeepCopy() *SIPDispatchRuleDirect {
	if in == nil {
		return nil
	}
	out := new(SIPDispatchRuleDirect)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPDispatchRuleIndividual) DeepCopyInto(out *SIPDispatchRuleIndividual) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPDispatchRuleIndividual.
func (in *SIPDispatchRuleIndividual) DeepCopy() *SIPDispatchRuleIndividual {
	if in == nil {
		return nil
	}
	out := new(SIPDispatchRuleIndividual)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPDispatchRuleList) DeepCopyInto(out *SIPDispatchRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SIPDispatchRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPDispatchRuleList.
func (in *SIPDispatchRuleList) DeepCopy() *SIPDispatchRuleList {
	if in == nil {
		return nil
	}
	out := new(SIPDispatchRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SIPDispatchRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPDispatchRuleSpec) DeepCopyInto(out *SIPDispatchRuleSpec) {
	*out = *in
	out.LivekitRef = in.LivekitRef
	if in.Direct != nil {
		in, out := &in.Direct, &out.Direct
		*out = new(SIPDispatchRuleDirect)
		**out = **in
	}
	if in.Individual != nil {
		in, out := &in.Individual, &out.Individual
		*out = new(SIPDispatchRuleIndividual)
		**out = **in
	}
	if in.Callee != nil {
		in, out := &in.Callee, &out.Callee
		*out = new(SIPDispatchRuleCallee)
		**out = **in
	}
	if in.TrunkIDs != nil {
		in, out := &in.TrunkIDs, &out.TrunkIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InboundNumbers != nil {
		in, out := &in.InboundNumbers, &out.InboundNumbers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Numbers != nil {
		in, out := &in.Numbers, &out.Numbers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RoomConfig != nil {
		in, out := &in.RoomConfig, &out.RoomConfig
		*out = new(RoomConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPDispatchRuleSpec.
func (in *SIPDispatchRuleSpec) DeepCopy() *SIPDispatchRuleSpec {
	if in == nil {
		return nil
	}
	out := new(SIPDispatchRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPDispatchRuleStatus) DeepCopyInto(out *SIPDispatchRuleStatus) {
	*out = *in
	if in.LastSyncedAt != nil {
		in, out := &in.LastSyncedAt, &out.LastSyncedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPDispatchRuleStatus.
func (in *SIPDispatchRuleStatus) DeepCopy() *SIPDispatchRuleStatus {
	if in == nil {
		return nil
	}
	out := new(SIPDispatchRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPInboundTrunk) DeepCopyInto(out *SIPInboundTrunk) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPInboundTrunk.
func (in *SIPInboundTrunk) DeepCopy() *SIPInboundTrunk {
	if in == nil {
		return nil
	}
	out := new(SIPInboundTrunk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SIPInboundTrunk) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPInboundTrunkList) DeepCopyInto(out *SIPInboundTrunkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SIPInboundTrunk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPInboundTrunkList.
func (in *SIPInboundTrunkList) DeepCopy() *SIPInboundTrunkList {
	if in == nil {
		return nil
	}
	out := new(SIPInboundTrunkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SIPInboundTrunkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPInboundTrunkSpec) DeepCopyInto(out *SIPInboundTrunkSpec) {
	*out = *in
	out.LivekitRef = in.LivekitRef
	if in.Numbers != nil {
		in, out := &in.Numbers, &out.Numbers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedAddresses != nil {
		in, out := &in.AllowedAddresses, &out.AllowedAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedNumbers != nil {
		in, out := &in.AllowedNumbers, &out.AllowedNumbers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AuthSecretRef != nil {
		in, out := &in.AuthSecretRef, &out.AuthSecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HeadersToAttributes != nil {
		in, out := &in.HeadersToAttributes, &out.HeadersToAttributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AttributesToHeaders != nil {
		in, out := &in.AttributesToHeaders, &out.AttributesToHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RingingTimeout != nil {
		in, out := &in.RingingTimeout, &out.RingingTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxCallDuration != nil {
		in, out := &in.MaxCallDuration, &out.MaxCallDuration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPInboundTrunkSpec.
func (in *SIPInboundTrunkSpec) DeepCopy() *SIPInboundTrunkSpec {
	if in == nil {
		return nil
	}
	out := new(SIPInboundTrunkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPInboundTrunkStatus) DeepCopyInto(out *SIPInboundTrunkStatus) {
	*out = *in
	if in.LastSyncedAt != nil {
		in, out := &in.LastSyncedAt, &out.LastSyncedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPInboundTrunkStatus.
func (in *SIPInboundTrunkStatus) DeepCopy() *SIPInboundTrunkStatus {
	if in == nil {
		return nil
	}
	out := new(SIPInboundTrunkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPNumber) DeepCopyInto(out *SIPNumber) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPNumber.
func (in *SIPNumber) DeepCopy() *SIPNumber {
	if in == nil {
		return nil
	}
	out := new(SIPNumber)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SIPNumber) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPNumberList) DeepCopyInto(out *SIPNumberList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SIPNumber, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPNumberList.
func (in *SIPNumberList) DeepCopy() *SIPNumberList {
	if in == nil {
		return nil
	}
	out := new(SIPNumberList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SIPNumberList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPNumberReference) DeepCopyInto(out *SIPNumberReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPNumberReference.
func (in *SIPNumberReference) DeepCopy() *SIPNumberReference {
	if in == nil {
		return nil
	}
	out := new(SIPNumberReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPNumberSpec) DeepCopyInto(out *SIPNumberSpec) {
	*out = *in
	if in.TrunkConfigRef != nil {
		in, out := &in.TrunkConfigRef, &out.TrunkConfigRef
		*out = new(SIPTrunkConfigReference)
		**out = **in
	}
	if in.LivekitRef != nil {
		in, out := &in.LivekitRef, &out.LivekitRef
		*out = new(LivekitReference)
		**out = **in
	}
	if in.AuthSecretRef != nil {
		in, out := &in.AuthSecretRef, &out.AuthSecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.AllowedAddresses != nil {
		in, out := &in.AllowedAddresses, &out.AllowedAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.KrispEnabled != nil {
		in, out := &in.KrispEnabled, &out.KrispEnabled
		*out = new(bool)
		**out = **in
	}
	if in.RingingTimeout != nil {
		in, out := &in.RingingTimeout, &out.RingingTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxCallDuration != nil {
		in, out := &in.MaxCallDuration, &out.MaxCallDuration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPNumberSpec.
func (in *SIPNumberSpec) DeepCopy() *SIPNumberSpec {
	if in == nil {
		return nil
	}
	out := new(SIPNumberSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPNumberStatus) DeepCopyInto(out *SIPNumberStatus) {
	*out = *in
	if in.LastSyncedAt != nil {
		in, out := &in.LastSyncedAt, &out.LastSyncedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPNumberStatus.
func (in *SIPNumberStatus) DeepCopy() *SIPNumberStatus {
	if in == nil {
		return nil
	}
	out := new(SIPNumberStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPOutboundTrunk) DeepCopyInto(out *SIPOutboundTrunk) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPOutboundTrunk.
func (in *SIPOutboundTrunk) DeepCopy() *SIPOutboundTrunk {
	if in == nil {
		return nil
	}
	out := new(SIPOutboundTrunk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SIPOutboundTrunk) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPOutboundTrunkList) DeepCopyInto(out *SIPOutboundTrunkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SIPOutboundTrunk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPOutboundTrunkList.
func (in *SIPOutboundTrunkList) DeepCopy() *SIPOutboundTrunkList {
	if in == nil {
		return nil
	}
	out := new(SIPOutboundTrunkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SIPOutboundTrunkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPOutboundTrunkSpec) DeepCopyInto(out *SIPOutboundTrunkSpec) {
	*out = *in
	out.LivekitRef = in.LivekitRef
	if in.Numbers != nil {
		in, out := &in.Numbers, &out.Numbers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AuthSecretRef != nil {
		in, out := &in.AuthSecretRef, &out.AuthSecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HeadersToAttributes != nil {
		in, out := &in.HeadersToAttributes, &out.HeadersToAttributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AttributesToHeaders != nil {
		in, out := &in.AttributesToHeaders, &out.AttributesToHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPOutboundTrunkSpec.
func (in *SIPOutboundTrunkSpec) DeepCopy() *SIPOutboundTrunkSpec {
	if in == nil {
		return nil
	}
	out := new(SIPOutboundTrunkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPOutboundTrunkStatus) DeepCopyInto(out *SIPOutboundTrunkStatus) {
	*out = *in
	if in.LastSyncedAt != nil {
		in, out := &in.LastSyncedAt, &out.LastSyncedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPOutboundTrunkStatus.
func (in *SIPOutboundTrunkStatus) DeepCopy() *SIPOutboundTrunkStatus {
	if in == nil {
		return nil
	}
	out := new(SIPOutboundTrunkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPTrunkConfig) DeepCopyInto(out *SIPTrunkConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPTrunkConfig.
func (in *SIPTrunkConfig) DeepCopy() *SIPTrunkConfig {
	if in == nil {
		return nil
	}
	out := new(SIPTrunkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SIPTrunkConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPTrunkConfigList) DeepCopyInto(out *SIPTrunkConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SIPTrunkConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPTrunkConfigList.
func (in *SIPTrunkConfigList) DeepCopy() *SIPTrunkConfigList {
	if in == nil {
		return nil
	}
	out := new(SIPTrunkConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SIPTrunkConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPTrunkConfigReference) DeepCopyInto(out *SIPTrunkConfigReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPTrunkConfigReference.
func (in *SIPTrunkConfigReference) DeepCopy() *SIPTrunkConfigReference {
	if in == nil {
		return nil
	}
	out := new(SIPTrunkConfigReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPTrunkConfigSpec) DeepCopyInto(out *SIPTrunkConfigSpec) {
	*out = *in
	out.LivekitRef = in.LivekitRef
	if in.AuthSecretRef != nil {
		in, out := &in.AuthSecretRef, &out.AuthSecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.AllowedAddresses != nil {
		in, out := &in.AllowedAddresses, &out.AllowedAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RingingTimeout != nil {
		in, out := &in.RingingTimeout, &out.RingingTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxCallDuration != nil {
		in, out := &in.MaxCallDuration, &out.MaxCallDuration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPTrunkConfigSpec.
func (in *SIPTrunkConfigSpec) DeepCopy() *SIPTrunkConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SIPTrunkConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPTrunkConfigStatus) DeepCopyInto(out *SIPTrunkConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPTrunkConfigStatus.
func (in *SIPTrunkConfigStatus) DeepCopy() *SIPTrunkConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SIPTrunkConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}
