//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressConfig) DeepCopyInto(out *EgressConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressConfig.
func (in *EgressConfig) DeepCopy() *EgressConfig {
	if in == nil {
		return nil
	}
	out := new(EgressConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EgressConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressConfigList) DeepCopyInto(out *EgressConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EgressConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressConfigList.
func (in *EgressConfigList) DeepCopy() *EgressConfigList {
	if in == nil {
		return nil
	}
	out := new(EgressConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EgressConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressConfigSpec) DeepCopyInto(out *EgressConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressConfigSpec.
func (in *EgressConfigSpec) DeepCopy() *EgressConfigSpec {
	if in == nil {
		return nil
	}
	out := new(EgressConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressConfigStatus) DeepCopyInto(out *EgressConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressConfigStatus.
func (in *EgressConfigStatus) DeepCopy() *EgressConfigStatus {
	if in == nil {
		return nil
	}
	out := new(EgressConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LivekitReference) DeepCopyInto(out *LivekitReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LivekitReference.
func (in *LivekitReference) DeepCopy() *LivekitReference {
	if in == nil {
		return nil
	}
	out := new(LivekitReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPDispatchRule) DeepCopyInto(out *SIPDispatchRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPDispatchRule.
func (in *SIPDispatchRule) DeepCopy() *SIPDispatchRule {
	if in == nil {
		return nil
	}
	out := new(SIPDispatchRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SIPDispatchRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPDispatchRuleCallee) DeepCopyInto(out *SIPDispatchRuleCallee) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPDispatchRuleCallee.
func (in *SIPDispatchRuleCallee) DeepCopy() *SIPDispatchRuleCallee {
	if in == nil {
		return nil
	}
	out := new(SIPDispatchRuleCallee)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPDispatchRuleDirect) DeepCopyInto(out *SIPDispatchRuleDirect) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPDispatchRuleDirect.
func (in *SIPDispatchRuleDirect) DeepCopy() *SIPDispatchRuleDirect {
	if in == nil {
		return nil
	}
	out := new(SIPDispatchRuleDirect)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPDispatchRuleIndividual) DeepCopyInto(out *SIPDispatchRuleIndividual) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPDispatchRuleIndividual.
func (in *SIPDispatchRuleIndividual) DeepCopy() *SIPDispatchRuleIndividual {
	if in == nil {
		return nil
	}
	out := new(SIPDispatchRuleIndividual)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPDispatchRuleList) DeepCopyInto(out *SIPDispatchRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SIPDispatchRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPDispatchRuleList.
func (in *SIPDispatchRuleList) DeepCopy() *SIPDispatchRuleList {
	if in == nil {
		return nil
	}
	out := new(SIPDispatchRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SIPDispatchRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPDispatchRuleSpec) DeepCopyInto(out *SIPDispatchRuleSpec) {
	*out = *in
	out.LivekitRef = in.LivekitRef
	if in.Direct != nil {
		in, out := &in.Direct, &out.Direct
		*out = new(SIPDispatchRuleDirect)
		**out = **in
	}
	if in.Individual != nil {
		in, out := &in.Individual, &out.Individual
		*out = new(SIPDispatchRuleIndividual)
		**out = **in
	}
	if in.Callee != nil {
		in, out := &in.Callee, &out.Callee
		*out = new(SIPDispatchRuleCallee)
		**out = **in
	}
	if in.TrunkIDs != nil {
		in, out := &in.TrunkIDs, &out.TrunkIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InboundNumbers != nil {
		in, out := &in.InboundNumbers, &out.InboundNumbers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Numbers != nil {
		in, out := &in.Numbers, &out.Numbers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPDispatchRuleSpec.
func (in *SIPDispatchRuleSpec) DeepCopy() *SIPDispatchRuleSpec {
	if in == nil {
		return nil
	}
	out := new(SIPDispatchRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPDispatchRuleStatus) DeepCopyInto(out *SIPDispatchRuleStatus) {
	*out = *in
	if in.LastSyncedAt != nil {
		in, out := &in.LastSyncedAt, &out.LastSyncedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPDispatchRuleStatus.
func (in *SIPDispatchRuleStatus) DeepCopy() *SIPDispatchRuleStatus {
	if in == nil {
		return nil
	}
	out := new(SIPDispatchRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPInboundTrunk) DeepCopyInto(out *SIPInboundTrunk) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPInboundTrunk.
func (in *SIPInboundTrunk) DeepCopy() *SIPInboundTrunk {
	if in == nil {
		return nil
	}
	out := new(SIPInboundTrunk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SIPInboundTrunk) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPInboundTrunkList) DeepCopyInto(out *SIPInboundTrunkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SIPInboundTrunk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPInboundTrunkList.
func (in *SIPInboundTrunkList) DeepCopy() *SIPInboundTrunkList {
	if in == nil {
		return nil
	}
	out := new(SIPInboundTrunkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SIPInboundTrunkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPInboundTrunkSpec) DeepCopyInto(out *SIPInboundTrunkSpec) {
	*out = *in
	out.LivekitRef = in.LivekitRef
	if in.Numbers != nil {
		in, out := &in.Numbers, &out.Numbers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedAddresses != nil {
		in, out := &in.AllowedAddresses, &out.AllowedAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedNumbers != nil {
		in, out := &in.AllowedNumbers, &out.AllowedNumbers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AuthSecretRef != nil {
		in, out := &in.AuthSecretRef, &out.AuthSecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HeadersToAttributes != nil {
		in, out := &in.HeadersToAttributes, &out.HeadersToAttributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AttributesToHeaders != nil {
		in, out := &in.AttributesToHeaders, &out.AttributesToHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RingingTimeout != nil {
		in, out := &in.RingingTimeout, &out.RingingTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxCallDuration != nil {
		in, out := &in.MaxCallDuration, &out.MaxCallDuration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPInboundTrunkSpec.
func (in *SIPInboundTrunkSpec) DeepCopy() *SIPInboundTrunkSpec {
	if in == nil {
		return nil
	}
	out := new(SIPInboundTrunkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPInboundTrunkStatus) DeepCopyInto(out *SIPInboundTrunkStatus) {
	*out = *in
	if in.LastSyncedAt != nil {
		in, out := &in.LastSyncedAt, &out.LastSyncedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPInboundTrunkStatus.
func (in *SIPInboundTrunkStatus) DeepCopy() *SIPInboundTrunkStatus {
	if in == nil {
		return nil
	}
	out := new(SIPInboundTrunkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPOutboundTrunk) DeepCopyInto(out *SIPOutboundTrunk) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPOutboundTrunk.
func (in *SIPOutboundTrunk) DeepCopy() *SIPOutboundTrunk {
	if in == nil {
		return nil
	}
	out := new(SIPOutboundTrunk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SIPOutboundTrunk) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPOutboundTrunkList) DeepCopyInto(out *SIPOutboundTrunkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SIPOutboundTrunk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPOutboundTrunkList.
func (in *SIPOutboundTrunkList) DeepCopy() *SIPOutboundTrunkList {
	if in == nil {
		return nil
	}
	out := new(SIPOutboundTrunkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SIPOutboundTrunkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPOutboundTrunkSpec) DeepCopyInto(out *SIPOutboundTrunkSpec) {
	*out = *in
	out.LivekitRef = in.LivekitRef
	if in.Numbers != nil {
		in, out := &in.Numbers, &out.Numbers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AuthSecretRef != nil {
		in, out := &in.AuthSecretRef, &out.AuthSecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HeadersToAttributes != nil {
		in, out := &in.HeadersToAttributes, &out.HeadersToAttributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AttributesToHeaders != nil {
		in, out := &in.AttributesToHeaders, &out.AttributesToHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPOutboundTrunkSpec.
func (in *SIPOutboundTrunkSpec) DeepCopy() *SIPOutboundTrunkSpec {
	if in == nil {
		return nil
	}
	out := new(SIPOutboundTrunkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SIPOutboundTrunkStatus) DeepCopyInto(out *SIPOutboundTrunkStatus) {
	*out = *in
	if in.LastSyncedAt != nil {
		in, out := &in.LastSyncedAt, &out.LastSyncedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SIPOutboundTrunkStatus.
func (in *SIPOutboundTrunkStatus) DeepCopy() *SIPOutboundTrunkStatus {
	if in == nil {
		return nil
	}
	out := new(SIPOutboundTrunkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}
